[package]
name = "butterfly"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17.0"
log = "0.4.17"
wasm-logger = "0.2.0"
